<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0;">
    <meta name="format-detection" content="telephone=no"/>
  </head>
  <body>
    <div style="min-width: 400px; max-width: 860px; border: 1px solid #004b77; padding: 20px 40px 30px; font: 12px/18px Arial, sans-serif; color: #38393a; background: white;">
      <div style="float: left;margin: 0 150px 0 0; ">
        <a href=""><img src="http://192.210.216.238:8066/modernpos/_inc/model/logo.png" style="border: none;"/></a>
      </div><br>
      <div style="margin-bottom: 50px;"><?php date("l, jS F, Y h:i:s", time()) ?></div>
      <div style="clear: both;"></div>
      <table border="0" cellpadding="0" cellspacing="0" align="center" style=" margin-bottom: 10px;max-width: 240px; min-width: 120px; border-collapse: collapse; border-spacing: 0; padding: 0;">
	  
	  <p align="left"><b>PONDO NETWORK<b><br>https://pondo.co.id/</p>
	  <p align="left">Congratulations, your account has been registered with the pondo network.<br>
Please login using the Pondo Network Application.</p>
        <tr>
        </tr>
      </table>
      <table cellpadding="0" cellspacing="0" border="0" width="100%" style="font: 12px/16px Arial, sans-serif; color: #4c4d4f; margin-bottom: 10px;">
      <tr>
        <th style="padding: 6px 8px; border: 1px solid #7f9eb1; color: white; background: #ff4c57; text-align: left;">EMAIL ID</th>
        <th style="padding: 6px 8px; border-top: 1px solid #7f9eb1; border-bottom: 1px solid #7f9eb1; border-right: 1px solid #7f9eb1; color: white; background: #ff4c57; text-align: center;">PASSWORD</th>
      </tr>
      <tr>
        <td valign="top" style="padding: 6px 8px; border-left: 1px solid #a59f93; border-right: 1px solid #a59f93; border-bottom: 1px solid #a59f93; color: #004b77;"><?php echo $id_user; ?></td>
        <td valign="top" style="padding: 6px 8px; border-right: 1px solid #a59f93; border-bottom: 1px solid #a59f93; text-align: center;"> <?php echo $pass_user; ?></td>
      </tr>
      </table>
      <div style="margin-bottom: 10px;">
        Please note that password is case-sensitive.
      </div>
      <div style="margin-bottom: 30px; font-weight: bold;">
        Best regards,<br/>
		PONDO NETWORK MANAGEMENT
      </div>
      <div style="font-size: 11px; line-height: 17px; border-top: 1px solid #004b77; padding-top: 6px;">
        This email is automatically generated by system, please do not reply to this address.<br/>
        For further questions please contact us at:<br/>
        - phone: Aceh (0821 2323 4747), or<br/>
        - email: <a href="mailto:customer.service@pondo.co.id">customer.service@pondo.co.id</a>
      </div>
    </div>
  </body>
</html>